### ISSUE TITLE
How does one create a Pause Text with multiple lines?

### ISSUE THREAD

**Issue by rjbprime** [Zombiefleischer/pause-text#15]
I have the above question. I am trying to make the following text output centered over my Pause Icon.

```
Game Paused!
Unable to
move Tokens!
```

Can there be a guide or a wiki created for this?

I originally used the "Prettier Login" module to do the custom text and render it, but it doesn't seem to work in v11.

**Comment by Zombiefleischer** [comment]
Unfortunately you can't do that here. The script splits at every newline and atm there is no way around it. If I had more time to learn more javascript, maybe I could build something, but unfortunately not right now. You can try it with the original module from which I build this one: https://gitlab.com/Freeze020/pause-icon/
