### ISSUE TITLE
Conflict with Ripper93's Tidbits

### ISSUE THREAD

**Issue by Nedrapter** [Zombiefleischer/pause-text#22]
Tidbits by TheRipper93 is a module that allows customization of the pause text (to a greater extend than this module) plus loading screens. Both modules offer awesome results together except one thing: The Font size set by this module is ignored when Tidbits is active. I've posted the conflict issue on Ripper's discord but from what I understood the conflict can be resolved from this module's side.
![image](https://github.com/Zombiefleischer/pause-text/assets/74311190/cd12a988-92eb-4a98-9822-d7db01456801)
Is this something you could adjust please?

**Comment by Nedrapter** [comment]
Also adding that if the module is needed, TheRipper93 can provide it for free.
![image](https://github.com/Zombiefleischer/pause-text/assets/74311190/9a14dfa3-0554-41b2-ac8e-d12216719b1c)

**Comment by Zombiefleischer** [comment]
I'm already subscribed to him, so no need for that. If I understand you correctly, you want to change the text size of Tidbits Pause Texts with my Modules "Font Size" setting, right?

**Comment by Nedrapter** [comment]
You are correct. Currently the tidbits negates your font size settings.On May 22, 2024 15:30, Zombiefleischer ***@***.***> wrote:
I'm already subscribed to him, so no need for that. If I understand you correctly, you want to change the text size of Tidbits Pause Texts with my Modules "Font Size" setting, right?
